### ISSUE TITLE
Cannot install kali

### ISSUE THREAD

**Issue by MostafaSoliman** [meefik/linuxdeploy#274]
please help, i have searched for 2 days on that problem wiz nothing.

My system:
Samsung galaxy s tab sm-t805
Rooted
Android 5.0.2

Every time i try to install kali i got this error 
![screenshot_2015-09-01-01-10-46](https://cloud.githubusercontent.com/assets/13528184/9592808/75063118-504f-11e5-905d-3b5fae744b35.png)

The following is the debug output:

Updating configuration file ... done
+ export 'PATH=/data/data/ru.meefik.linuxdeploy/linux/env/bin:/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin'
+ export 'LINUXDEPLOY_DIR=/data/data/ru.meefik.linuxdeploy/linux/env'
+ /data/data/ru.meefik.linuxdeploy/linux/env/bin/linuxdeploy install
+ msg >>> install
+ echo >>> install 
+ >>> install 
install_system
+ prepare_system
+ msg -n Checking mount points ... 
+ echo -n Checking mount points ... 
Checking mount points ... + grep -c  /data/data/ru.meefik.linuxdeploy/linux/env/mnt  /proc/mounts
done 
Checking installation path ... done 
Making new disk image (4000 MB) ... + local is_mnt=0
+ [ 0 -eq 0 ]
+ msg done
+ echo done 
+ msg -n Checking installation path ... 
+ echo -n Checking installation path ... 
+ [ -e /storage/emulated/0/kali.img -a ! -f /storage/emulated/0/kali.img ]
+ msg done
+ echo done 
+ [ file = file ]
+ [ 4000 -eq 0 ]
+ msg -n Making new disk image (4000 MB) ... 
+ echo -n Making new disk image (4000 MB) ... 
+ set -e
+ expr 4000 - 1
+ dd if=/dev/zero of=/storage/emulated/0/kali.img bs=1048576 seek=3999 count=1
dd: /storage/emulated/0/kali.img: Invalid argument
+ dd if=/dev/zero of=/storage/emulated/0/kali.img bs=1048576 count=4000
4000+0 records in
4000+0 records out
4194304000 bytes (3.9GB) copied, 76.135471 seconds, 52.5MB/s
done 
+ exit 0
+ [ 0 -eq 0 ]
+ msg done
+ echo done 
+ [ file = file -o file = partition ]
+ local fs_support=
+ grep -c ext4 /proc/filesystems
Making file system (ext4) ... + [ 1 -gt 0 ]
+ fs_support=ext4
+ break
+ [ -z ext4 ]
+ [ auto = auto ]
+ FS_TYPE=ext4
+ msg -n Making file system (ext4) ... 
+ echo -n Making file system (ext4) ... 
+ set -e
+ losetup+ grep -c /storage/emulated/0/kali.img -a

+ true
+ is_loop=0
+ grep -c /storage/emulated/0/kali.img /proc/mounts
+ true
+ is_raw=0
+ [ 0 -eq 0 -a 0 -eq 0 ]
+ mke2fs -qF -t ext4 -O ^has_journal /storage/emulated/0/kali.img
ext2fs_check_if_mount: Can't check if filesystem is mounted due to missing mtab file while determining whether /storage/emulated/0/kali.img is mounted.
+ exit 0
done 
Mounting partitions:  
/ ... + [ 0 -eq 0 ]
+ msg done
+ echo done 
+ [ file = ram ]
+ return 0
+ [ 0 -ne 0 ]
+ msg Mounting partitions: 
+ echo Mounting partitions:  
+ mount_system root binfmt_misc
+ [ 2 -eq 0 ]
+ [ 2 -gt 1 ]
+ mount_system root
+ [ 1 -eq 0 ]
+ [ 1 -gt 1 ]
+ msg -n / ... 
+ echo -n / ... 
+ grep -c  /data/data/ru.meefik.linuxdeploy/linux/env/mnt  /proc/mounts
+ local is_mnt=0
+ [ 0 -eq 0 ]
+ [ ! -d /data/data/ru.meefik.linuxdeploy/linux/env/mnt ]
+ [ -d /storage/emulated/0/kali.img ]
+ local mnt_opts=rw,relatime
+ mount -o rw,relatime /storage/emulated/0/kali.img /data/data/ru.meefik.linuxdeploy/linux/env/mnt
+ [ 0 -eq 0 ]
+ msg done
+ echodone 
 done 
+ return 0
+ [ 0 -eq 0 ]
+ mount_system binfmt_misc
+ [ 1 -eq 0 ]
+ [ 1 -gt 1 ]
+ local binfmt_dir=
+ [ -d /proc/sys/fs/binfmt_misc ]
/proc/sys/fs/binfmt_misc ... + binfmt_dir=/proc/sys/fs/binfmt_misc
+ [ -n /proc/sys/fs/binfmt_misc ]
+ msg -n /proc/sys/fs/binfmt_misc ... 
+ echo -n /proc/sys/fs/binfmt_misc ... 
+ mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
mount: mounting binfmt_misc on /proc/sys/fs/binfmt_misc failed: Device or resource busy
+ get_platform
+ local arch=
+ [ -z  ]
+ uname -m
+ arch=armv7l
+ echo arm
done 
Installing Debian-based distribution:  
+ local platform=arm
+ [ ! -e /proc/sys/fs/binfmt_misc/qemu-i386 ]
+ echo :qemu-i386:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x03\x00:\xff\xff\xff\xff\xff\xfe\xfe\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/local/bin/qemu-i386-static:
+ [ 0 -eq 0 ]
+ msg done
+ echo done 
+ return 0
+ [ 0 -eq 0 ]
+ return 0
+ [ 0 -ne 0 ]
+ msg Installing Debian-based distribution: 
+ echo Installing Debian-based distribution:  
+ local basic_packages=locales,sudo,man-db
+ [ -z  ]
+ DEBOOTSTRAP_DIR=/data/data/ru.meefik.linuxdeploy/linux/env/deploy/debootstrap
+ export DEBOOTSTRAP_DIR
+ ash -e /data/data/ru.meefik.linuxdeploy/linux/env/bin/debootstrap --no-check-gpg --arch armhf --foreign --extractor=ar --include=locales,sudo,man-db sana /data/data/ru.meefik.linuxdeploy/linux/env/mnt http://http.kali.org/kali/
/data/data/ru.meefik.linuxdeploy/linux/env/bin/debootstrap: line 354: tr: Permission denied
<<< install 
+ [ 126 -ne 0 ]
+ return 1
+ msg <<< install
+ echo <<< install 
+ exit 0

following the output of ls -l /data/data/ru..../linux/bin

![screenshot_2015-09-01-01-22-46](https://cloud.githubusercontent.com/assets/13528184/9592875/7c21c9b6-5050-11e5-8786-00c293acac48.png)
![screenshot_2015-09-01-01-22-36](https://cloud.githubusercontent.com/assets/13528184/9592878/919d0b98-5050-11e5-843b-d5f6844310d3.png)
![screenshot_2015-09-01-01-22-24](https://cloud.githubusercontent.com/assets/13528184/9592885/a678a9f0-5050-11e5-8c03-635a26b77826.png)

your help will be highly appreciated.

Thanks
Mostafa.

**Comment by meefik** [comment]
1) Max image size for FAT - 4095 Mb.
2) Try path to image /storage/emulated/legacy/
3) Install BusyBox, uncheck "Settings->Built-in shell" and run
"Settings->Update ENV".
01 сент. 2015 г. 2:28 пользователь "MostafaSoliman" <
notifications@github.com> написал:

**Comment by ssb3304** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

ssb3304@naver.com 님께 보내신 메일 <Re: [linuxdeploy] Cannot install kali (#274)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by MostafaSoliman** [comment]
i did what u asked , and reinstalled linux deploy , i can now procced to another error
![screenshot_2015-09-01-20-38-49](https://cloud.githubusercontent.com/assets/13528184/9613690/9e01103c-50f5-11e5-8965-e5c852be1efa.png)

**Comment by meefik** [comment]
Please try this version, I added chmod 755 before execute /debootstrap/debootstrap.
https://yadi.sk/d/t4vPJuIFios5J

**Comment by MostafaSoliman** [comment]
Dear meefik,
I am afraid i have the same problem , if need any data to provide please let me know
![screenshot_2015-09-01-22-07-16](https://cloud.githubusercontent.com/assets/13528184/9615172/332c7aee-50ff-11e5-993e-817caf2098d7.png)

**Comment by meefik** [comment]
We need to understand why there is an error:

    /debootstrap/debootstrap: Premission denied

LD calls the command:

    MNT_TARGET=/data/data/ru.meefik.linuxdeploy/linux/mnt
    chroot ${MNT_TARGET} /debootstrap/debootstrap --second-stage

What outputs the command?

    ls -l /data/data/ru.meefik.linuxdeploy/linux/mnt/debootstrap/
    ls -l /data/data/ru.meefik.linuxdeploy/linux/mnt/bin/

Most likely a problem with namespaces.

**Comment by meefik** [comment]
You can also try this:

    su --mount-master
    chroot /data/data/ru.meefik.linuxdeploy/linux/mnt /debootstrap/debootstrap --second-stage

**Comment by MostafaSoliman** [comment]
Dear meefik ,
My mnt/ is embty as shown
![screenshot_2015-09-02-00-32-24](https://cloud.githubusercontent.com/assets/13528184/9618835/a5f52856-5112-11e5-87cd-db62f3bedcd7.png)

**Comment by MostafaSoliman** [comment]
Here are some other tries 
![screenshot_2015-09-02-10-28-23](https://cloud.githubusercontent.com/assets/13528184/9626387/e4be69dc-5165-11e5-8670-ebac5b7525a9.png)

**Comment by MostafaSoliman** [comment]
I run reconfigure command , now i have data in /mnt folder,

HYG
![screenshot_2015-09-02-15-53-12](https://cloud.githubusercontent.com/assets/13528184/9633085/8cc4dd78-5193-11e5-86f0-d4e8dfd2b349.png)
![Uploading Screenshot_2015-09-02-15-52-43.png…]()

**Comment by MostafaSoliman** [comment]
HYG

**Comment by MostafaSoliman** [comment]
i tried to reconfigure , now i got data in mnt

![screenshot_2015-09-02-15-52-43](https://cloud.githubusercontent.com/assets/13528184/9633580/43a1329c-5196-11e5-9ab7-97831d5edcab.png)
![screenshot_2015-09-02-15-53-12](https://cloud.githubusercontent.com/assets/13528184/9633634/72eb5190-5196-11e5-941c-c8fd836252db.png)

**Comment by meefik** [comment]
Disable "mount namespaces seporation" from settings SuperSU (if it used for root).
https://su.chainfire.eu/#how-mount

**Comment by meefik** [comment]
It seems the problem is solved. Try version 1.5.2-159.

**Comment by MostafaSoliman** [comment]
But i still can't  start the ssh service , would you please provide link for that version

Many thanks for your support

**Comment by MostafaSoliman** [comment]
Dear meefik,

I  run  
su --mount-master
export PATH=$PATH:/usr/bin:/usr/sbin:/bin:/sbin
chroot /data/data/ru.meefik.linuxdeploy/linux/mnt /debootstrap/debootstrap --second-stage
![screenshot_2015-09-03-10-45-41](https://cloud.githubusercontent.com/assets/13528184/9661694/8c2cf36a-5264-11e5-8c53-8ab0508e7f1f.png)
![screenshot_2015-09-03-10-45-37](https://cloud.githubusercontent.com/assets/13528184/9661695/8c3e5a10-5264-11e5-8b32-3daf87fa5466.png)

su --mount-master
/data/data/ru.meefik.linuxdeploy/linux/bin/linuxdeploy shell "/debootstrap/debootstrap --second-stage"

![screenshot_2015-09-03-10-56-25](https://cloud.githubusercontent.com/assets/13528184/9661803/0eaf5a26-5265-11e5-8958-533f4f781bbb.png)

I tried to reconfig or start 
![screenshot_2015-09-02-15-53-12](https://cloud.githubusercontent.com/assets/13528184/9661848/50824940-5265-11e5-9083-dec18fca8608.png)

**Comment by meefik** [comment]
https://github.com/meefik/linuxdeploy/releases/tag/1.5.2

**Comment by MostafaSoliman** [comment]
Will try it and feedback sir

**Comment by MostafaSoliman** [comment]
This version  works fine many thanks meefik for your prompt  support  😊😊

**Comment by Dan-Wolfy** [comment]
Looks like this has returned with 1.5.3-168
