### ISSUE TITLE
Failure while installing base packages

### ISSUE THREAD

**Issue by riramar** [meefik/linuxdeploy#555]
Fresh Linux Deploy installation and when I tried to install Kali Linux (rolling) I'm getting the error "Failure while installing base packages".

**Comment by riramar** [comment]
These are the last lines from /data/local/linux/debootstrap/debootstrap.log:

dpkg: version 230-7 of systemd already installed, skipping
dpkg: regarding .../systemd-sysv_230-7_armhf.deb containing systemd-sysv, pre-dependency problem:
 systemd-sysv pre-depends on systemd
  systemd is unpacked, but has never been configured.

dpkg: error processing archive /var/cache/apt/archives/systemd-sysv_230-7_armhf.deb (--unpack):
 pre-dependency problem - not installing systemd-sysv
dpkg: version 3.35 of tasksel already installed, skipping
dpkg: version 3.35 of tasksel-data already installed, skipping
dpkg: version 230-7 of udev already installed, skipping
dpkg: version 2:7.4.1829-1 of vim-common already installed, skipping
dpkg: version 2:7.4.1829-1 of vim-tiny already installed, skipping
dpkg: version 1.18-2+b1 of wget already installed, skipping
dpkg: version 0.52.18-3 of whiptail already installed, skipping
Errors were encountered while processing:
 /var/cache/apt/archives/init_1.37kali1_armhf.deb
 /var/cache/apt/archives/systemd-sysv_230-7_armhf.deb

**Comment by Spliddo** [comment]
It seems that the issue is with rolling. Try installing sana with GNOME at ext2

**Comment by riramar** [comment]
Installing sana it worked! :)
I'll try to do the distupgrade.

**Comment by snooops** [comment]
If you want to use Sana, use this URL: http://old.kali.org/kali/

**Comment by vapor99** [comment]
Sana is old though.  :(  Meefik, please fix Kali Rolling.  :-1:

**Comment by Sultannn** [comment]
Fixed in version 2.0-beta2: https://github.com/meefik/linuxdeploy/releases/tag/2.0.0

Closed

**Comment by snooops** [comment]
well the repo url is afaik not fixed

Am 14.09.2016 4:19 nachm. schrieb "Sultannn" <notifications@github.com>:

**Comment by Megaeloelo** [comment]
Can someone fix that?

**Comment by shubhamagarwal3010** [comment]
I'm facing error "package /var/cache/apt/archives/systemd-shim_10-3_amd64.deb is at fault", "E: Package 'systemd-shim' has no installation candidate"
