### ISSUE TITLE
The newest Arch still doesn't work with 2.1.1.

### ISSUE THREAD

**Issue by 948171624** [meefik/linuxdeploy#986]
Old issue here. https://github.com/meefik/linuxdeploy/issues/971
After 2.1.1's fix, arch is still not work, even cannot start ssh, dbus.
[ldoutput.log](https://github.com/meefik/linuxdeploy/files/2306205/ldoutput.log)
Here is log.
Maybe solution editing nsswitch mentioned in #971 is not a proper way.
Please recheck it. Thanks a lot.

**Comment by meefik** [comment]
You must reinstall or reconfigure the container.

**Comment by 948171624** [comment]
@meefik I've already made a fresh install.

**Comment by meefik** [comment]
Please put here your /etc/group

**Comment by 948171624** [comment]
root:x:0:root
user:x:1000:
aid_system:x:1000:user,root
aid_radio:x:1001:user,root
aid_bluetooth:x:1002:user,root
aid_graphics:x:1003:user,root
aid_input:x:1004:user,root
aid_audio:x:1005:user,root
aid_camera:x:1006:user,root
aid_log:x:1007:user,root
aid_compass:x:1008:user,root
aid_mount:x:1009:user,root
aid_wifi:x:1010:user,root
aid_adb:x:1011:user,root
aid_install:x:1012:user,root
aid_media:x:1013:user,root
aid_dhcp:x:1014:user,root
aid_sdcard_rw:x:1015:user,root
aid_vpn:x:1016:user,root
aid_keystore:x:1017:user,root
aid_usb:x:1018:user,root
aid_drm:x:1019:user,root
aid_available:x:1020:user,root
aid_gps:x:1021:user,root
aid_media_rw:x:1023:user,root
aid_mtp:x:1024:user,root
aid_drmrpc:x:1026:user,root
aid_nfc:x:1027:user,root
aid_sdcard_r:x:1028:user,root
aid_clat:x:1029:user,root
aid_loop_radio:x:1030:user,root
aid_media_drm:x:1031:user,root
aid_package_info:x:1032:user,root
aid_sdcard_pics:x:1033:user,root
aid_sdcard_av:x:1034:user,root
aid_sdcard_all:x:1035:user,root
aid_logd:x:1036:user,root
aid_shared_relro:x:1037:user,root
aid_shell:x:2000:user,root
aid_cache:x:2001:user,root
aid_diag:x:2002:user,root
aid_net_bt_admin:x:3001:user,root
aid_net_bt:x:3002:user,root
aid_inet:x:3003:user,root
aid_net_raw:x:3004:user,root
aid_net_admin:x:3005:user,root
aid_net_bw_stats:x:3006:user,root
aid_net_bw_acct:x:3007:user,root
aid_net_bt_stack:x:3008:user,root
usbmux:x:140:

ps. even ssh fail, but vnc works fine.

**Comment by meefik** [comment]
Ok, I will deal with the problem.

**Comment by meefik** [comment]
Fixed in version 2.1.1-239

**Comment by 948171624** [comment]
@meefik The 2.1.1(240) version still doesn't work. ssh/dbus of a fresh install Arch start fail. 
[ldoutput.log](https://github.com/meefik/linuxdeploy/files/2312460/ldoutput.log)

**Comment by meefik** [comment]
@948171624 Do you tried a new installation?

**Comment by 948171624** [comment]
I upgrade the app from googleplay, and in app, i click install and wait for complete reinstall.
(I am not reinstall the app itself)

**Comment by meefik** [comment]
Can you put here your latest /etc/group?

**Comment by 948171624** [comment]
root:x:0:root
user:x:1000:
aid_system:x:1000:user,root
aid_radio:x:1001:user,root
aid_bluetooth:x:1002:user,root
aid_graphics:x:1003:user,root
aid_input:x:1004:user,root
aid_audio:x:1005:user,root
aid_camera:x:1006:user,root
aid_log:x:1007:user,root
aid_compass:x:1008:user,root
aid_mount:x:1009:user,root
aid_wifi:x:1010:user,root
aid_adb:x:1011:user,root
aid_install:x:1012:user,root
aid_media:x:1013:user,root
aid_dhcp:x:1014:user,root
aid_sdcard_rw:x:1015:user,root
aid_vpn:x:1016:user,root
aid_keystore:x:1017:user,root
aid_usb:x:1018:user,root
aid_drm:x:1019:user,root
aid_available:x:1020:user,root
aid_gps:x:1021:user,root
aid_media_rw:x:1023:user,root
aid_mtp:x:1024:user,root
aid_drmrpc:x:1026:user,root
aid_nfc:x:1027:user,root
aid_sdcard_r:x:1028:user,root
aid_clat:x:1029:user,root
aid_loop_radio:x:1030:user,root
aid_media_drm:x:1031:user,root
aid_package_info:x:1032:user,root
aid_sdcard_pics:x:1033:user,root
aid_sdcard_av:x:1034:user,root
aid_sdcard_all:x:1035:user,root
aid_logd:x:1036:user,root
aid_shared_relro:x:1037:user,root
aid_shell:x:2000:user,root
aid_cache:x:2001:user,root
aid_diag:x:2002:user,root
aid_net_bt_admin:x:3001:user,root
aid_net_bt:x:3002:user,root
aid_inet:x:3003:user,root
aid_net_raw:x:3004:user,root
aid_net_admin:x:3005:user,root
aid_net_bw_stats:x:3006:user,root
aid_net_bw_acct:x:3007:user,root
aid_net_bt_stack:x:3008:user,root
usbmux:x:140:

**Comment by meefik** [comment]
I can't reproduce it. Try the following steps:

1. stop your container
2. restart your device
3. reinstall this app (remove and install again)
4. run a new Arch Linux installation

**Comment by 948171624** [comment]
What I do:
1. stop&uninstall&delete the img&reboot
2. install app from play
3. install arch as before
4. It still has problem. Here is debug output.
>>> start
[15:28:21] Checking file system ... done
[15:28:21] Mounting the container: 
[15:28:21] / ... done
[15:28:21] /proc ... done
[15:28:21] /sys ... done
[15:28:21] /dev ... done
[15:28:21] /dev/shm ... skip
[15:28:21] /dev/pts ... done
[15:28:21] ## bootstrap/rootfs : do_start
[15:28:21] ## bootstrap/archlinux : do_start
[15:28:21] ## core/emulator : do_start
[15:28:21] ## core/motd : do_start
[15:28:21] ## core/hosts : do_start
[15:28:21] ## core/hostname : do_start
[15:28:21] ## core/mnt : do_start
[15:28:21] :: Mounting partitions: 
[15:28:21] /sdcard ... done
[15:28:21] :: Configuring core/mnt ... 
[15:28:21] ## core/net : do_start
[15:28:21] :: Configuring core/net ... 
[15:28:21] ## core/timezone : do_start
[15:28:21] ## core/su : do_start
[15:28:21] ## core/locale : do_start
[15:28:21] ## core/profile : do_start
[15:28:21] ## core/aid : do_start
[15:28:21] ## core/sudo : do_start
[15:28:21] ## core/unchroot : do_start
[15:28:21] ## core : do_start
[15:28:21] ## bootstrap : do_start
[15:28:21] ## desktop/desktop-base : do_start
[15:28:21] ## extra : do_start
[15:28:21] ## desktop/dbus : do_start
[15:28:22] :: Starting desktop/dbus ... dbus[21541]: Unknown username "colord" in message bus configuration file
[15:28:22] dbus[21541]: Unknown username "systemd-timesync" in message bus configuration file
[15:28:22] dbus[21541]: Unknown username "systemd-network" in message bus configuration file
[15:28:22] dbus[21541]: Unknown username "systemd-resolve" in message bus configuration file
[15:28:22] dbus[21541]: Unknown username "rtkit" in message bus configuration file
[15:28:22] dbus[21541]: Unknown username "avahi" in message bus configuration file
[15:28:22] dbus[21541]: Unknown group "network" in message bus configuration file
[15:28:22] dbus[21541]: Unknown username "polkitd" in message bus configuration file
[15:28:22] dbus[21541]: Unknown username "polkitd" in message bus configuration file
[15:28:22] dbus-daemon[21541]: Failed to start message bus: Could not get UID and GID for username "dbus"
[15:28:22] fail
[15:28:22] ## desktop/xfce : do_start
[15:28:22] ## desktop : do_start
[15:28:22] ## extra/pulse : do_start
[15:28:22] ## extra/ssh : do_start
[15:28:25] :: Starting extra/ssh ... Privilege separation user nobody does not exist
[15:28:25] fail
[15:28:25] ## graphics/vnc : do_start
[15:28:25] :: Starting graphics/vnc ... xauth:  file /home/user/.Xauthority does not exist
[15:28:28] 
[15:28:28] New 'localhost:0 (user)' desktop is localhost:0
[15:28:28] 
[15:28:28] Creating default config /home/user/.vnc/config
[15:28:28] Starting applications specified in /home/user/.vnc/xstartup
[15:28:28] Log file is /home/user/.vnc/localhost:0.log
[15:28:28] done
[15:28:28] ## graphics : do_start
[15:28:28] <<< start

Note: My phone is zh_CN locale, and I do installation with en_US.UTF8 and username 'user'.
Note2: kali works fine for me. I will test arch on my another phone.

**Comment by meefik** [comment]
Can you give me a full log of the installation in trace mode?

**Comment by 948171624** [comment]
This is a full log (debug+trace mode).
[installoutput.log](https://github.com/meefik/linuxdeploy/files/2314048/installoutput.log)
